### ISSUE TITLE
error when I start build for container

### ISSUE THREAD

**Issue by hcalebe** [apluslms/run-aplus-front#11]
hello , I juste test building with docker build for test before start deveolppement 
but I have this error : 
(I hope that anyone can help me to solve that. Thanks )

It appears that the specific errors are as follows:

E: Unable to locate package python3-lxml
E: Unable to locate package python3-lz4
E: Unable to locate package python3-pillow
E: Unable to locate package redis

this is my error : 

![image](https://github.com/apluslms/run-aplus-front/assets/160108647/d7e64bf1-b269-48d8-867e-bc6ea74c3d26)
![image](https://github.com/apluslms/run-aplus-front/assets/160108647/a2b54b89-97ae-4ff1-b57d-368f6d9a29ed)

Message : 

root@ubuntu:/home/sysadmin/memoire/run-aplus-docker/back-run-aplus-front# docker build -t test-aplus-front:v1 .
[+] Building 111.5s (7/8)                                                                                                                                                                                          docker:default
 => [internal] load build definition from Dockerfile                                                                                                                                                                         0.0s
 => => transferring dockerfile: 1.90kB                                                                                                                                                                                       0.0s
 => [internal] load metadata for docker.io/apluslms/service-base:django-1.18                                                                                                                                                 0.0s
 => [internal] load .dockerignore                                                                                                                                                                                            0.0s
 => => transferring context: 2B                                                                                                                                                                                              0.0s
 => [internal] load build context                                                                                                                                                                                            0.0s
 => => transferring context: 1.75kB                                                                                                                                                                                          0.0s
 => [1/4] FROM docker.io/apluslms/service-base:django-1.18                                                                                                                                                                   0.0s
 => CACHED [2/4] COPY rootfs /                                                                                                                                                                                               0.0s
 => ERROR [3/4] RUN :  && apt_install       python3-lxml       python3-lz4       python3-pillow       redis  && adduser --system --no-create-home --disabled-password --gecos "A+ webapp server,,," --home /srv/aplus --i  111.4s
------
 > [3/4] RUN :  && apt_install       python3-lxml       python3-lz4       python3-pillow       redis  && adduser --system --no-create-home --disabled-password --gecos "A+ webapp server,,," --home /srv/aplus --ingroup nogroup aplus  && mkdir /srv/aplus && chown aplus.nogroup /srv/aplus  && git config --global --add safe.directory /srv/aplus  && cd /srv/aplus  && git clone --quiet --single-branch --branch v1.21.0 https://github.com/apluslms/a-plus.git .  && (echo "On branch $(git rev-parse --abbrev-ref HEAD) | $(git describe)"; echo; git log -n5) > GIT  && rm -rf .git  && python3 -m compileall -q .  && pip_install       -r requirements.txt       "django-debug-toolbar >= 3.8.1"       flower  && rm requirements.txt  && find /usr/local/lib/python* -type d -regex '.*/locale/[a-z_A-Z]+' -not -regex '.*/\(en\|fi\|sv\)' -print0 | xargs -0 rm -rf  && find /usr/local/lib/python* -type d -name 'tests' -print0 | xargs -0 rm -rf  && export     APLUS_SECRET_KEY="-"     APLUS_CACHES="{"default": {"BACKEND": "django.core.cache.backends.dummy.DummyCache"}}"  && python3 manage.py compilemessages 2>&1  && create-db.sh aplus aplus django-migrate.sh   && mkdir -p /var/celery/results  && chown -R aplus:nogroup /var/celery  && ::
111.3 W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Temporary failure resolving 'deb.debian.org'
111.3 W: Failed to fetch http://deb.debian.org/debian-security/dists/bullseye-security/InRelease  Temporary failure resolving 'deb.debian.org'
111.3 W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/InRelease  Temporary failure resolving 'deb.debian.org'
111.3 W: Some index files failed to download. They have been ignored, or old ones used instead.
111.4 E: Unable to locate package python3-lxml
111.4 E: Unable to locate package python3-lz4
111.4 E: Unable to locate package python3-pillow
111.4 E: Unable to locate package redis
------
Dockerfile:12
--------------------
  11 |     ARG BRANCH=v1.21.0
  12 | >>> RUN : \
  13 | >>>  && apt_install \
  14 | >>>       python3-lxml \
  15 | >>>       python3-lz4 \
  16 | >>>       python3-pillow \
  17 | >>>       redis \
  18 | >>> \
  19 | >>>   # create user
  20 | >>>  && adduser --system --no-create-home --disabled-password --gecos "A+ webapp server,,," --home /srv/aplus --ingroup nogroup aplus \
  21 | >>>  && mkdir /srv/aplus && chown aplus.nogroup /srv/aplus \
  22 | >>>  && git config --global --add safe.directory /srv/aplus \
  23 | >>> \
  24 | >>>  && cd /srv/aplus \
  25 | >>>   # clone and prebuild .pyc files
  26 | >>>  && git clone --quiet --single-branch --branch $BRANCH https://github.com/apluslms/a-plus.git . \
  27 | >>>  && (echo "On branch $(git rev-parse --abbrev-ref HEAD) | $(git describe)"; echo; git log -n5) > GIT \
  28 | >>>  && rm -rf .git \
  29 | >>>  && python3 -m compileall -q . \
  30 | >>> \
  31 | >>>   # install requirements, remove the file, remove unrequired locales and tests
  32 | >>>  && pip_install \
  33 | >>>       -r requirements.txt \
  34 | >>>       "django-debug-toolbar >= 3.8.1" \
  35 | >>>       flower \
  36 | >>>  && rm requirements.txt \
  37 | >>>  && find /usr/local/lib/python* -type d -regex '.*/locale/[a-z_A-Z]+' -not -regex '.*/\(en\|fi\|sv\)' -print0 | xargs -0 rm -rf \
  38 | >>>  && find /usr/local/lib/python* -type d -name 'tests' -print0 | xargs -0 rm -rf \
  39 | >>> \
  40 | >>>   # preprocess
  41 | >>>  && export \
  42 | >>>     APLUS_SECRET_KEY="-" \
  43 | >>>     APLUS_CACHES="{\"default\": {\"BACKEND\": \"django.core.cache.backends.dummy.DummyCache\"}}" \
  44 | >>>  && python3 manage.py compilemessages 2>&1 \
  45 | >>>  && create-db.sh aplus aplus django-migrate.sh \
  46 | >>>  \
  47 | >>>  && mkdir -p /var/celery/results \
  48 | >>>  && chown -R aplus:nogroup /var/celery \
  49 | >>>  && :
  50 |
--------------------
ERROR: failed to solve: process "/bin/sh -c :  && apt_install       python3-lxml       python3-lz4       python3-pillow       redis  && adduser --system --no-create-home --disabled-password --gecos \"A+ webapp server,,,\" --home /srv/aplus --ingroup nogroup aplus  && mkdir /srv/aplus && chown aplus.nogroup /srv/aplus  && git config --global --add safe.directory /srv/aplus  && cd /srv/aplus  && git clone --quiet --single-branch --branch $BRANCH https://github.com/apluslms/a-plus.git .  && (echo \"On branch $(git rev-parse --abbrev-ref HEAD) | $(git describe)\"; echo; git log -n5) > GIT  && rm -rf .git  && python3 -m compileall -q .  && pip_install       -r requirements.txt       \"django-debug-toolbar >= 3.8.1\"       flower  && rm requirements.txt  && find /usr/local/lib/python* -type d -regex '.*/locale/[a-z_A-Z]+' -not -regex '.*/\\(en\\|fi\\|sv\\)' -print0 | xargs -0 rm -rf  && find /usr/local/lib/python* -type d -name 'tests' -print0 | xargs -0 rm -rf  && export     APLUS_SECRET_KEY=\"-\"     APLUS_CACHES=\"{\\\"default\\\": {\\\"BACKEND\\\": \\\"django.core.cache.backends.dummy.DummyCache\\\"}}\"  && python3 manage.py compilemessages 2>&1  && create-db.sh aplus aplus django-migrate.sh   && mkdir -p /var/celery/results  && chown -R aplus:nogroup /var/celery  && :" did not complete successfully: exit code: 100
root@ubuntu:/home/sysadmin/memoire/run-aplus-docker/back-run-aplus-front#

**Comment by ihalaij1** [comment]
Looks like you are unable to connect to ``deb.debian.org`` due to some network issue.
If you are using a VM maybe this command helps: ``docker build --network host -t test-aplus-front:v1 .``
