### ISSUE TITLE
Add lz4 to the container

### ISSUE THREAD

**Issue by veeraalt** [apluslms/run-aplus-front#4]
After the PR https://github.com/apluslms/a-plus/pull/575, lz4 compression library (https://pypi.org/project/lz4/) is used as a default compressor to compress HTML pages in cache. It should be added to the test container too.

**Comment by jaguarfi** [comment]
but, why is the https://github.com/veeraalt/a-plus/blob/cf139b51ab1530d72496ed32062e35fb815bcbe7/requirements.txt#L16 commented?

**Comment by raphendyr** [comment]
Because it's a optional requirement. And it's optional, because it's better to be installed as OS package due to binary files. Commented entry in the requirements.txt is a documentation. If the `setup.py` were used, then the `extras_require` would be a better tool for that.
